//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tokyo_stock_exchanges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub local_code: String,
    #[sea_orm(column_type = "Text")]
    pub english_name: String,
    #[sea_orm(column_type = "Text")]
    pub japanese_name: String,
    pub section: String,
    pub sector33_code: Option<i16>,
    pub sector17_code: Option<i16>,
    pub size_code: Option<i16>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
