[package]
name = "ipc-if"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
ts-rs = { version = "10.1.0", features = ["chrono-impl"] }