// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SampleQuery = { query: string | null, };

export type SampleResponse = { id: number, title: string, body: string, };
