// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokyoStockExchangeImportQuery = { japanese_file: string | null, english_file: string | null, };
